### ISSUE TITLE
Preferred way to call leaflet-draw JS and CSS

### ISSUE THREAD

**Issue by loganbrunner** [urutau-nz/dashboard-chap#3]
Right now am pulling leaflet-draw from the CDN, but could instead place them in the repo like with the other libraries.

`index.php`
```
    <!-- TODO: Could do these 2 like leaflet-measure-master in the css-links.php and js-scripts.php files -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
```

@dean-mcbean - is this preferred (for load times)?

**Comment by dean-mcbean** [comment]
Nah, it's fine either way. The reason our other libraries are downloaded is because I don't think they were offered by CDNs, and I wanted to be able to easily read/edit them if needs be.

We can always download leaflet-draw later if we decide to
